[package]
name = "bustubx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "0.34.0"
petgraph = "0.6.3"
lazy_static = "1.4.0"
itertools = "0.11.0"